// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sszyujezyguwafptmxup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzenl1amV6eWd1d2FmcHRteHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NjEzNzIsImV4cCI6MjA1MTAzNzM3Mn0.x3FfYvoTygMUwnZ5V3Y1iBggfQeMryzQEv8ZO86NTic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);